TEST_RUN = False
API_SERVER = 'http://localhost:8000'
WORKER_KEY = ''
BROKER_HOST = "localhost"
BROKER_PORT = 5672
BROKER_USER = "ersatz"
BROKER_PASSWORD = ""
BROKER_VHOST = "ersatz"
AWS_ACCESS_KEY = ""
AWS_SECRET_KEY = ""
S3_BUCKET = ''

LOGLEVEL = 'INFO'

PROJECT_DIR = None
SPEARMINT = None
CONVNET = None
WORKING_DIR = None
S3_CACHEDIR = None
RUN_IN_SUBPROCESS = False
MRNN_DP_START_PORT = 8008
MRNN_DP_MAX_PORT = 8100
DATASET_VERSION = 1

LOCAL_SETUP = False
S3_ROOT = None
